Feat/landingpage
tobiasmeyhoefer/bitz pull request #37
Opened 2024-05-20 18:14 UTC by Wolkenwolf9

2024-05-20 18:57 UTC, tobiasmeyhoefer requested changes

2024-05-20 18:57 UTC, tobiasmeyhoefer commented on components/ui/icons.tsx
hier bitte nicht alle icons in eine Datei bringen der bessere approach:

im Verzeichnis public ein Verzeichnis svg oder icons machen und da alle Bilder rein jeweils als .svg file, dann kannst du diese über Next Image einbinden Image src="test" und test importierst du dann oben z.B. so "import test from "@/public/svg/test.svg""

2024-05-21 09:43 UTC, Wolkenwolf9 commented
Hab die Icons über den Public Folder implementiert, einen Scroll-to-top  Button hinzugefügt und einen Indikator zu Scrollen auf der ersten Section habe auch in die Global Css smooth scrolling enabled

2024-05-21 12:07 UTC, tobiasmeyhoefer approved these changes

2024-05-21 12:07 UTC, merged